### ISSUE TITLE
Add an interface that allows to add patterns at any time

### ISSUE THREAD

**Issue by likaisoft** [G-Research/ahocorasick_rs#102]
First of all, I have to say the lib is amazingly fast, especially compared with a pure Python implementation.
Then I wish there will be an interface that allows the patterns to be added at any time.
Currently, patterns can only be added in one go.  Some patterns are dynamically generated and it would be beneficial to be able to add them on-the-fly.
Thanks

**Comment by BurntSushi** [comment]
I don't maintain this wrapper library, but I do maintain the underlying Rust library. I can definitively say that this will never happen. Most of the optimizations depend on knowing all of the patterns up-front. Supporting an incremental interface is just not practical for the level of optimization being employed here.

If you need to support dynamically growing an Aho-Corasick automaton, you can either use another library that does support it (although it is likely slower), or you can roll your own. At that point, it will just be the standard algorithm without much frills. A third option is to build your own incremental data structure on top of what this library provides, perhaps by using multiple AC automatons, but that could be pretty complicated.

**Comment by itamarst** [comment]
Based on @BurntSushi 's comment above, going to close this; if the underlying library won't support it, the Python wrapper won't either, sorry.
