### ISSUE TITLE
Method find_matches_as_indexes return byte indices

### ISSUE THREAD

**Issue by necrosovereign** [G-Research/ahocorasick_rs#12]
`AhoCorasick.find_matches_as_indexes` doesn't work as expected for non-ASCII strings. It returns byte indices, which leads to surprising results.

Example:
```python
>>> ac = AhoCorasick(["foo"])
>>> haystack = "äfoo" # or haystack = "\xe4foo"
>>> ac.find_matches_as_indexes(haystack)
[(0, 2, 5)]
>>> haystack[2:5]
'oo'
>>> haystack_as_bytes = bytes(haystack, encoding='utf8')
>>> haystack_as_bytes[2:5]
b'foo'
```
So `find_matches_as_indexes` returns incorrect indices for `haystack`, but they are correct for the corresponding byte array. I think it should be made explicit in the documentation.

**Comment by BurntSushi** [comment]
See: https://github.com/BurntSushi/aho-corasick/issues/72

**Comment by necrosovereign** [comment]
Yes, I understand why the method works like this. But, from a point of view of a Python programmer, it's surprising that a method that takes a string doesn't return string indices, so the documentation of the method should mention this.

**Comment by itamarst** [comment]
Yeah, that's arguably a bug. I will change the API to match Python programmer expectations.

**Comment by itamarst** [comment]
Options:

1. Drop the API.
2. Convert to _Python's_ interpretation of what a unicode character is for indexes. It appears to be... code points.
3. Only accept ASCII.

**Comment by itamarst** [comment]
Will probably go with option 2, since I can borrow BurntSushi's example.

**Comment by itamarst** [comment]
Release 0.10.1 is now available with this fix.
