### ISSUE TITLE
Problem with MATCHKIND_LEFTMOST_FIRST

### ISSUE THREAD

**Issue by nguyenhuuthuat09** [G-Research/ahocorasick_rs#20]
Hi, thank you for great library.

I am facing a problem with `MATCHKIND_LEFTMOST_FIRST` setting:

```
from ahocorasick_rs import *
patterns = ["234", "345", "123"]
haystack = "123456"

ac = AhoCorasick(patterns, matchkind=MATCHKIND_LEFTMOST_FIRST)
ac.find_matches_as_strings(haystack)
# return ['123']
```

Same problem happen with `MATCHKIND_LEFTMOST_LONGEST`.

I think it should return `234` because `234` is the `leftmost` element in `patterns`.

If I am wrong or misunderstood, please correct me. 

And can you please add feature `MATCHKIND_LONGEST` so that it can return all the longest pattern even if they have the same length (not only the `leftmost` one).

Thanks again for your great library.

**Comment by BurntSushi** [comment]
(I'm not the author of this library, but I am the author of the underlying Rust library.)

The "leftmost" here doesn't refer to the leftmost pattern, but rather, the leftmost position in the haystack. The match of `123` is indeed correct. The "leftmost" match kind is meant to be used when you want successive non-overlapping matches. The "first" and "longest" variants are two different ways of discriminating between how to select matches at various positions. The "first" variant says, "return the leftmost match corresponding to the pattern that appears first in the constructor of Aho-Corasick." The "longest" variant says, "return the leftmost match corresponding to the longest possible pattern in the constructor of Aho-Corasick." This is explained in a lot more detail in the docs: https://docs.rs/aho-corasick/latest/aho_corasick/enum.MatchKind.html

I think what you want is to have the library report overlapping matches (documented in the README). Then you can pick which match you want.

**Comment by stackedsax** [comment]
Thanks, @BurntSushi, for the helpful comments.  It's really nice of you to hop over and explain things. 

Thanks for the library in the first place!

**Comment by nguyenhuuthuat09** [comment]
Thank you @BurntSushi for the clear explanation.

**Comment by itamarst** [comment]
Re-opening since this will probably be recurring question? So should maybe... copy/paste more detailed explanation/examples from the Rust docs.

**Comment by itamarst** [comment]
OK, I've updated the README with more prose, more examples, and link to the underlying Rust library's docs.
