### ISSUE TITLE
Function signatures

### ISSUE THREAD

**Issue by vitalie-cracan** [G-Research/ahocorasick_rs#52]
Thank you for this module. There's something wrong with function signatures or my VS Code setup, as I do not get much information about function arguments: 

`(function) find_matches_as_indexes: Any`

Would you know what's going wrong?

**Comment by itamarst** [comment]
I never really added any type signature documentation, basically. Would you like to submit a PR?

**Comment by itamarst** [comment]
(You are under no obligation to do so, obviously; if you don't it'll get added to the todo list.)

**Comment by itamarst** [comment]
My guess is it needs a `.pyi` file: https://mypy.readthedocs.io/en/stable/stubs.html

**Comment by itamarst** [comment]
Oh but you'd need to make maturin know about it, which is a bit more work if you've never done it so maybe easier if I just do it.

**Comment by itamarst** [comment]
0.14 should be out soon (later today? otherwise tomorrow) with this included.
