### ISSUE TITLE
Allow the usage of NFA

### ISSUE THREAD

**Issue by dalf** [G-Research/ahocorasick_rs#53]
In a project I'm working on, we are using  ahocorasick_rs with millions of patterns.
The DFA option uses a lot of memory which prevent the usage of multiprocessing (not related to ahocorasick_rs but in the same code).
Also, this make testing difficult because of the expensive setup.

Is it be possible to add an option to chose between DFA and NFA? (contiguous  and/or noncontiguous NFA).

Use case: annotate [PubMed](https://en.wikipedia.org/wiki/PubMed) with [ChEBI](https://en.wikipedia.org/wiki/ChEBI)  and other terminologies.

**Comment by itamarst** [comment]
0.14 should be out shortly with this included. Thank you for the help!
