### ISSUE TITLE
Thank you for your work!

### ISSUE THREAD

**Issue by AlexMikhalev** [G-Research/ahocorasick_rs#61]
Hello @itamarst and other contributors, normally you see issues here, but I wanted to praise and give you credit for the work you have done:
I built a pipeline using pyahocorasick automata as part of a fairly sophisticated ML pipeline https://github.com/applied-knowledge-systems/the-pattern , see pipeline 1. (which won https://redis.com/blog/build-on-redis-hackathon-winners/), and I was thinking of moving pipeline to Rust (even had a very nice email exchange with Andrew @burntSushi). However, I need HTTP fetch, and new RedisGears version 2  (using wasm runtime still doesn't have HTTP fetch), so I still rely on Python for the server-side pipeline. 
Your work allows me to build a transition from Python pyahocorasick to Rust based Aho-Corasick. 
Thank you.

**Comment by itamarst** [comment]
Thank you!
