### ISSUE TITLE
Please provide wheels for Python 3.12

### ISSUE THREAD

**Issue by nijel** [G-Research/ahocorasick_rs#85]
Python 3.12 has been released, and it would be great to have ahocorasick_rs wheels for it available at PyPI. Thanks.

**Comment by itamarst** [comment]
Remaining todos:

* [ ] Upgrade to PyO3 0.20 where there's official support for Python 3.12 [(here's the PR)](https://github.com/PyO3/pyo3/pull/3493)
* [ ] Do the actual release of this package

**Comment by itamarst** [comment]
Packages should be up on PyPI shortly.
