### ISSUE TITLE
availabilty on conda

### ISSUE THREAD

**Issue by ericqu** [G-Research/ahocorasick_rs#96]
I can only install from Conda / Conda-forge at work; could the package also be published there?
I don't need immediate availability; some days or weeks are okay if it is helpful.

**Comment by itamarst** [comment]
Note that the nice thing about Conda-Forge is that anyone can package things there, doesn't have to be the package authors. So you could do it too: https://conda-forge.org/docs/maintainer/adding_pkgs.html#creating-recipes

In particular, if it's relevant to your job you could do this on work time, and knowing how to do it will presumably be helpful in other similar situations.

**Comment by itamarst** [comment]
Did you implement it/start implementing it? If so, let me know and I'll update docs when it's available. If you didn't, maybe re-open this issue for tracking purposes?
